name: Release
on:
  push:
    tags: ["v*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          generate_release_notes: true

  publish:
    name: Publish
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo publish -p shelle-macros --token ${{ secrets.CRATES_IO_TOKEN }}
      - run: cargo publish -p shelle --token ${{ secrets.CRATES_IO_TOKEN }}
